apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper-deployment
  labels:
    app: my-scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-scrapper
  template:
    metadata:
      labels:
        app: my-scrapper
    spec:
      containers:
      - name: my-scrapper
        image: mayurbotre95/my-scrapper:1.0.4
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: my-scrapper
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31006
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scrapper-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dummy-domain.com
    http:
      paths:
      - path: /scrapy
        pathType: Prefix
        backend:
          service:
            name: scrapper-service
            port:
              number: 5000